import {
  Svg, PngImage,
  Rect, RoundedRect, Square, Circle, Ellipse, Line, Polyline, Polygon, Path,
  UnitLine, HLine, VLine, Dot, Triangle,
  Text, Span,
  Box, Frame,
  HStack, VStack, Spacer, Grid,
  Group,
  Graph,
  Node, Edge, Network,
  Overlay, TransformBox, Rotate, Attach, Anchor,
  CoordLine, Spline, RoundedLine, Segments, Arc, Fill, HFill, VFill,
  Arrow, ArrowHead, Ray, Points,
  Bar, VBar, HBar, Bars, VBars, HBars,
  Axis, HAxis, VAxis, Scale, HScale, VScale, Label, HLabel, VLabel,
  Labels, HLabels, VLabels, Mesh, HMesh, VMesh, Mesh2D,
  Plot, BarPlot, Legend, LegendItem, OuterLabel,
  TextStack, TextRow, TextCol, TextGrid, TextBox, TextFrame, TextFigure,
  TitleBox, TitleFrame, Bullets, Slide,
  SymLine, SymSpline, SymPoly, SymPoints, SymFill, Field, SymField,
} from '@gum-jsx/core'
import {
  MathSpan, MathSymbol, MathSpacer, MathRule,
  MathRow, MathText, MathChoice, MathCol, MathBox, Latex, Tex,
  MathOp, SupSub, Frac, Sqrt, Bracket, TextMode, MathArray,
  Accent, Underline, Overline, MathStretch, HorizBrace, XArrow,
  Phantom, Smash, Lap, Enclose, RaiseBox, VCenter, Pmb,
} from '@gum-jsx/math'
import { GeoMap } from '@gum-jsx/maps'

// Keep the supported names explicit. Besides giving GUM useful property types,
// this avoids accidentally treating exported helpers as element constructors.
const DEFAULT_ELEMENTS = Object.freeze({
  Svg, PngImage,
  Rect, RoundedRect, Square, Circle, Ellipse, Line, Polyline, Polygon, Path,
  UnitLine, HLine, VLine, Dot, Triangle,
  Text, Span,
  Box, Frame,
  HStack, VStack, Spacer, Grid,
  Group,
  Graph, GeoMap,
  Node, Edge, Network,
  Overlay, TransformBox, Rotate, Attach, Anchor,
  CoordLine, Spline, RoundedLine, Segments, Arc, Fill, HFill, VFill,
  Arrow, ArrowHead, Ray, Points,
  Bar, VBar, HBar, Bars, VBars, HBars,
  Axis, HAxis, VAxis, Scale, HScale, VScale, Label, HLabel, VLabel,
  Labels, HLabels, VLabels, Mesh, HMesh, VMesh, Mesh2D,
  Plot, BarPlot, Legend, LegendItem, OuterLabel,
  TextStack, TextRow, TextCol, TextGrid, TextBox, TextFrame, TextFigure,
  TitleBox, TitleFrame, Bullets, Slide,
  SymLine, SymSpline, SymPoly, SymPoints, SymFill, Field, SymField,
  MathSpan, MathSymbol, MathSpacer, MathRule,
  MathRow, MathText, MathChoice, MathCol, MathBox, Latex, Tex,
  MathOp, SupSub, Frac, Sqrt, Bracket, TextMode, MathArray,
  Accent, Underline, Overline, MathStretch, HorizBrace, XArrow,
  Phantom, Smash, Lap, Enclose, RaiseBox, VCenter, Pmb,
})

export { DEFAULT_ELEMENTS }
